on: [push]
name: Run the action

jobs:
  setup-sfdx-action:
    runs-on: ubuntu-latest
    name: Setup SFDX
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup SFDX
        uses: ./
        with:
          plugins: skuid-sfdx
      - name: Validate SFDX
        run: |
          sfdx --version
          sfdx plugins

  setup-sfdx-action-no-plugins:
    runs-on: ubuntu-latest
    name: Setup SFDX
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup SFDX
        uses: ./
      - name: Validate SFDX
        run: |
          sfdx --version
